[package]
name = "jit-liquidity-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
eyre = "0.6"
dotenv = "0.15.0"
alloy = { version = "0.8", features = ["full", "node-bindings"] }
