name: Rust

on:
  push:
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust.yml'

env:
  CARGO_TERM_COLOR: always
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: |
          chmod +x ./run-tests.sh
          ./run-tests.sh
        shell: bash
        env:
          TEST_PRIVATE_KEY: ${{ vars.TEST_PRIVATE_KEY }}
          INFURA_URL: ${{ secrets.INFURA_URL }}
          INFURA_WS_URL: ${{ secrets.INFURA_WS_URL }}
          INFURA_URL_BLOCK: ${{ vars.INFURA_URL_BLOCK }}
