name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  INFURA_URL: ${{ secrets.INFURA_URL }}
  PRIVATE_URL: ${{ secrets.PRIVATE_URL }}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache Foundry
      uses: actions/cache@v3
      with:
        path: ~/.foundry
        key: ${{ runner.os }}-foundry

    - name: Install Foundry
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        source /home/runner/.bashrc
        foundryup

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
