name: Rust

on:
  push:
    branches: [ "master", "dev_ops" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  INFURA_URL: ${{ secrets.INFURA_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: |
          chmod +x ./run-tests.sh
          ./run-tests.sh
        shell: bash
        env:
          ANVIL_ENDPOINT: http://127.0.0.1:8545
